### ISSUE TITLE
Segmentation fault in undexta

### ISSUE THREAD

**Issue by pb-cdunn** [thegenemyers/DEXTRACTOR#10]
```
$ dexta -k foo.fasta
$ mv foo.dexta bar.dexta
$ undexta -vk bar.dexta
Program received signal SIGSEGV, Segmentation fault.
0x0000000000402d29 in Uncompress_Read (len=-51042,
    s=0x611030 "aaggattttcaacttttccaatactagtgtaaattcaagggaaaggaaaaactgcacatctaatccatcagcacgattttgcatccatctctcttcaaactctcttcagatatcaaataatctctctgaacagcttaagcctgactacacgcggctgctgcagcatctctctgtgtgagacagccagcaaggataaaatc"...) at DB.c:296
296       s[len] = 4;
```
This occurred after a significant portion of the file was processed, definitely more than a couple reads:
```
$ ls -l
-rw-rw-r-- 1 cdunn Domain Users     8388608 Jun 11 12:25 bar.fasta
-rw-rw-r-- 1 cdunn Domain Users 14471167024 Jun 11 11:48 foo.fasta

$ grep -c '>' bar.fasta
598
```
* PacificBiosciences/FALCON#383

I'll try to debug...

**Comment by thegenemyers** [comment]
Actually do you have any reads in the file that are longer than 2^16?
that may be the problem as the code was written back at a time when
reads were assumed to not be so long.   A casual glance at the code
seems to reveal that it is assuming so.

    -- Gene

**Comment by pb-cdunn** [comment]
Possibly. I hit this bug just moments before I had to leave for my fiance's show. And now I'm traveling to Menlo Park. But your guess is probably right.

**Comment by pb-cdunn** [comment]
There are definitely many lines longer than 32k, but none longer than 64k. (They were filtered at 50k, and I double-checked.) Also, it did not crash on a long line.

I ran **valgrind** but learned nothing:
```
==5463== Process terminating with default action of signal 11 (SIGSEGV)
==5463==  Bad permissions for mapped region at address 0x51EF92E
==5463==    at 0x402D29: Uncompress_Read (DB.c:296)
==5463==    by 0x401ADB: main (undexta.c:184)
```

**Comment by thegenemyers** [comment]
Since its crashing when undext'ing the 598th read, perhaps you could 
take a subset of
the big data set, say the first 600 reads and reproduce the error with 
that.  If the error
reproduces on the smaller data set, then you should be able to send it 
by email to me
and I can definitely then do the debug at my end.
    -- Gene

**Comment by pb-cdunn** [comment]
I have a repro with truncated input, 10MB. (The real input is 14GB, 237M lines, 1063154 reads. Btw, I'd like to diff the truncated output from **dexta** against the input fasta, but **undexta** does not capitalize or allow me to set the column-width.) So I could send that to you if we don't find the problem.

For the failure, the (truncated) output has much bigger well numbers:
```
$  grep '>' input.fasta
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/6/0_12833
>m151124_152824_42161_c100947332550000001823216206251626_s1_p0/49/414_2371
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/8/0_11366
>m151124_152824_42161_c100947332550000001823216206251626_s1_p0/66/1205_3829
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/16/0_2217
>m151124_152824_42161_c100947332550000001823216206251626_s1_p0/69/0_7615
...
$ grep '>' output.fasta
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/6/0_12833 RQ=0.0
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/49/414_2371 RQ=0.0
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/264/0_11366 RQ=0.0
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/322/1205_3829 RQ=0.0
```
So the problem is (probably) the order of SMRT cells, again! We need to fix our data. However, the crash is still interesting. Here is the tail of the the output, just before the crash:
```
$ grep '>' output.fasta | tail
...
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/91457/0_6472 RQ=0.0
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/91526/63646_12604 RQ=0.0
```

Here is something unrelated, but interesting. This succeeds:
```
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/6/0_60
AAAAAAAAAAAAAGAGAGATCAGGAAAGATCCAACAGAAACAGCAATGTAGATCACTGCT
```
But this fails:
```
>m151129_221014_sherri_c100947162550000001823216206251657_s1_p0/6/0_12833
AAAAAAAAAAAAAGAGAGATCAGGAAAGATCCAACAGAAACAGCAATGTAGATCACTGCT
```
    undexta: System error, read failed!

Not the same problem, but apparently something parses the header to determine read-length.

And this is interesting:
```
foo:master$ head -n 138283 foo.fasta >| short.fasta
foo:master$ time dexta -k short.fasta
Line 138284: Fasta line is too long (> 99998 chars)
```
That happens when the last line is a header, which is bad input.

**Comment by thegenemyers** [comment]
Chris, could you email the input to me so I can debug.  I do think it is 
still the large pulse numbers,
any pulse number over 2^16 would I believe break the code.  I had 
originally been using short ints
for pulse numbers, including in Dazzler DB's and DAM's but later changed 
it in the DB's and DAM's
and probably just didn't think about reflecting it back into the 
compression tools since I never personally
use them (the compressors for the DB routines assume int's).
     -- Gene

**Comment by pb-cdunn** [comment]
https://downloads.pacbcloud.com/public/dataset/dexta-segv.tgz

**Comment by thegenemyers** [comment]
Hi Chris,

    Sorry for the long pause on this, just been awfully busy.  I was 
working on
fixing the cause of the crash which is due to using uint16's to encode 
the pulse
numbers which in the new data sets go above 65K and hence overflow.

     However, I also now observe that short.fasta is a complete 
interleaving of two
different SMRT runs.  There are two distinct prefix codes in each 
header, interleaved,
and well numbers are not in increasing order.  Both of these things blow 
the assumptions
that dexta makes about a .fasta file that it is being given to it and 
therefore won't work.

     I'll fix the overflow problem shortly now, but the other "misuse" I 
cannot do anything
about.  My recollection is we had talked about this some time ago and 
you had realized
that somewhere earlier in your pipeline some bam related step was 
sorting and mixing
up all the reads.  So hopefully this is not an issue for you going forward.

    -- Gene

**Comment by thegenemyers** [comment]
Christopher,

     I've fixed the source of the crash (pulse #'s that don't fit in a 
uint16) and
committed the fix.  The issue also affected dexqv and undexqv which have 
also
been fixed.

      But as I said in my previous response, your .fasta file violates 
the assumptions
of the dexta compressor (reads from different SMRT's all intermingled), 
so although
it won't crash when being compressed, the .fasta file obtained on 
decompression
is garbled.

    -- Gene

**Comment by pb-cdunn** [comment]
> The issue also affected dexqv and undexqv which have also been fixed.

Excellent! Thanks, Gene.

> I also now observe that short.fasta is a complete interleaving of two different SMRT runs.
> ...
> My recollection is [that] you had realized that somewhere earlier in your pipeline some bam related step was sorting and mixing up all the reads. So hopefully this is not an issue for you going forward.

No, not an issue anymore. I even snuck that fix into an older release of smrtlink.
